var nome = "Guilherme";
var idade = 28;
var comidaFavorita;
comidaFavorita = "Pizza";
var lutador, altura, peso, vitorias, derrotas;
lutador = "Jon Jones";
altura = 1.93;
peso = 93;
vitorias = 26;
derrotas = 1;
console.log("Nome: " + nome);
console.log("Idade: " + idade);
console.log("Comida Favorita: " + comidaFavorita);
console.log("Lutador: " + lutador);
console.log("Altura: " + altura + " m");
console.log("Peso: " + peso + " kg");
console.log("Vitórias: " + vitorias);
console.log("Derrotas: " + derrotas);
